# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unity',
            options={'verbose_name_plural': 'Units'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cod',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cod',
            new_name='code',
        ),
    ]
