# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20181002_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(default=1, help_text='Code of store', max_length=45),
            preserve_default=False,
        ),
    ]
