# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20181002_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unity',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unity',
            new_name='unit',
        ),
    ]
